Absorb resources from items based on amount in stack
stonepillars/goon-flock pull request #153
Opened 2022-04-13 02:07 UTC by FlameArrow57

[BUG]

## About the PR 
This PR makes it so that resources gained from reclaimed items are based on the amount of items in the stack.

The speed at which items that are a stack are reclaimed wasn't changed, I wasn't sure how that should be handled.

## Why's this needed? 
Bug fix, fixes #80.

2022-04-13 17:39 UTC, amylizzle commented
yeah, I don't think this is the right way to do it. I tried picking up a stack of floor tiles, and it ate them nearly instantly and gave me almost 1000 resources at once.

Maybe instead have the consuming do it's thing and decrement the stack count by one instead.

2022-04-13 17:49 UTC, amylizzle approved these changes

2022-04-13 19:55 UTC, amylizzle commented
er..github is having a moment, I did not approve this, I approved a different PR :|

2022-04-13 19:56 UTC, amylizzle commented on code/mob/living/critter/flock/flockdrone.dm
> +		src.resources += src.absorb_per_health * absorb * I.amount
```suggestion
		src.resources += src.absorb_per_health * absorb 
	        I.amount--
```

2022-04-13 19:56 UTC, amylizzle requested changes
change to eat one item at a time

2022-04-13 20:14 UTC, amylizzle commented on code/mob/living/critter/flock/flockdrone.dm
> +		src.resources += src.absorb_per_health * absorb * I.amount
note - this might be part of the fix, but it is not the whole fix

2022-04-13 21:37 UTC, amylizzle commented
> Yeah, I was able to get it so that the total time it takes to eat a stack of items is the sum of the times of each individual item, but might be kind of hard to remove individual items from the stack, I would have to spend more time on that. The whole stack has one health value.

It has an amount though, you could grab the health value, tick it down, when it's <=0 decrease item count, and reset health to max again?

2022-04-14 12:05 UTC, stonepillars commented
Playing cards are `W_CLASS_TINY`, and so are their boxes. It may be better to rebalance based on `I.w_class`
If say, TINY items only gave 1 resource, then drones could only really get 52 resources from a deck of cards.
Stuff like cable coils are both tiny, and have an amount value, but unlike card decks do not have contents so drones can't
drop them in that way.

**If you want to just let the flock eat card decks all at once**, then just check if there's an amount and consume based on that, and then also ignore the contents check since you just ate it all at once.

If they're balanced based on that, then drones can easily prioritize yummier items (bigger items) and then gather around the pile of cards on the floor like a flock of birds like they're supposed to when they're done.

2022-05-06 17:05 UTC, stonepillars commented
Closed for design reasons. Very difficult to reconcile the fact when an item has a near-zero health it still retains full functionality which can give the flock an advantage in some circumstances. The serial approach will be used instead.

2022-05-06 17:05 UTC, closed without merging