Slight tweaks to flockdrone AI to prioritise building material deposits and conversion of walls/doors/closets
stonepillars/goon-flock pull request #24
Opened 2022-03-12 17:59 UTC by amylizzle

## About the PR 
Tweaks the AI priorities, moving depositing mats on tealprints higher and building tiles lower.
Also, when building is selected, prioritises conversion of doors, walls, and lockers to increase access to new materials for harvesting.

Fixes #11

2022-03-12 18:19 UTC, TobleroneSwordfish requested changes

2022-03-12 18:19 UTC, TobleroneSwordfish commented on code/mob/living/critter/ai/flock/flocktasks.dm
> +				. += PT
```suggestion
			. += priority_turfs
```

2022-03-12 18:19 UTC, TobleroneSwordfish commented on code/mob/living/critter/ai/flock/flocktasks.dm
> +//task priorities and preconditions at a glance:
that's going to end up desynched real fast (still worth doing I think)

2022-03-12 18:19 UTC, TobleroneSwordfish commented on code/mob/living/critter/ai/flock/flocktasks.dm
> +			istype(T, /turf/simulated/floor) && !istype(T, /turf/simulated/floor/feather)  && (locate(/obj/storage) in T))
use isfeathertile(T) since that works for all the feather checks

2022-03-12 18:19 UTC, TobleroneSwordfish commented on code/mob/living/critter/ai/flock/flocktasks.dm
> +				istype(T, /turf/simulated/wall) && !istype(T, /turf/simulated/wall/auto/feather))
isfeathertile(T) again

2022-03-12 18:59 UTC, amylizzle commented
made suggested changes both in my additions to the code and the other places they occurred in that file

2022-03-13 01:09 UTC, stonepillars commented
Leaving a game open for almost an hour to see what the drones do with no direction.
Drones very rarely ever made tiles. This sometimes led to drones getting stuck since they need a turf to phase through walls (though as a flockmind you can easily save them by making one yourself)
They did focus alot more on the walls and doors though, which is good.

2022-03-13 11:35 UTC, amylizzle commented
Yeah, that was my experience from testing also. My intention was basically to ensure you needed at least one drone fractured into flockbits, as well as preventing drones from wasting all their resources on things not useful to you.

I'm sure we'll end up tweaking this more as development goes on, but I think as a first pass it works.

2022-03-13 12:00 UTC, merged