Add Flock plating under Flock floortiles
stonepillars/goon-flock pull request #257
Opened 2022-05-05 04:52 UTC by FlameArrow57

[FEATURE]

## About the PR 
This PR adds a new Flock tile, a plating, meant to be inactive, not associated with any Flock. It is found under Flock floortiles.

![image](https://user-images.githubusercontent.com/53062374/166864149-8e2fc076-bbfb-4eca-ad68-67da80a21009.png)

It acts like typical plating, where you can put a floor tile on it to make it into a seemingly regular tile. Prying the floor tile off will reveal the Flock plating underneath.

## Why's this needed? 
It makes more sense for cases like when you build a Flock floortile in space, it's broken and pried up, and a Flock plating appears rather than a typical station plating tile.

It also further reinforces the idea that Flock conversion of a tile is full conversion.

2022-05-06 01:59 UTC, stonepillars commented
I don't really subscribe to the idea that it is a total conversion esp. on flock tiles- and these would be covered by either flock floors or normal floor tiles.

2022-05-07 07:30 UTC, ZeWaka requested changes

2022-05-07 07:30 UTC, ZeWaka commented on code/turf/turf.dm
> +/turf/proc/ReplaceWithFeatherPlating()
Why is this its own snowflake proc

2022-05-07 07:30 UTC, ZeWaka commented on code/turf/turf.dm
> +	var/flock_plating_under = FALSE
Doc Comments.

2022-05-07 07:30 UTC, ZeWaka commented on code/turf/turf_flock.dm
> +/turf/simulated/floor/feather_plating
Why is this not plating

2022-05-08 03:50 UTC, FlameArrow57 commented on code/turf/turf.dm
> +/turf/proc/ReplaceWithFeatherPlating()
Was for convenience, will remove

2022-05-08 03:50 UTC, FlameArrow57 commented on code/turf/turf.dm
> +	var/flock_plating_under = FALSE
Let me know if needs to be improved

2022-05-08 03:50 UTC, FlameArrow57 commented on code/turf/turf_flock.dm
> +/turf/simulated/floor/feather_plating
Done

2022-05-11 04:22 UTC, ZeWaka approved these changes

2022-05-21 22:47 UTC, stonepillars commented
!merge_upstream

2026-03-04 00:07 UTC, closed without merging