Prevents flockminds from teleporting to deleted drones
stonepillars/goon-flock pull request #94
Opened 2022-03-25 23:19 UTC by TobleroneSwordfish

[BUG[
## About the PR 
Fixes #79

## Why's this needed? 
bug bad

2022-03-26 18:48 UTC, stonepillars requested changes

2022-03-26 18:48 UTC, stonepillars commented on code/mob/living/intangible/flock/flockmind.dm
> +		if(origin && !origin.qdeled)
```suggestion
		if(!QDELETED(origin))
```
Checks if disposed or null

2022-03-26 22:35 UTC, TobleroneSwordfish commented on code/mob/living/intangible/flock/flockmind.dm
> +		if(origin && !origin.qdeled)
exactly what I was looking for, thanks

2022-03-27 23:18 UTC, stonepillars approved these changes

2022-03-27 23:18 UTC, merged